### ISSUE TITLE
Panchayat overview screen text

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#25]
**Time range dropdown text**
"All available dates"
"Past 60 days"
"Past 30 days"

**Intro text**
Can we add the following intro text somewhere at the top of the page -->
"The performance of your panchayats on average days to complete each step of the payment process."
At the end of the previous sentence, add a question mark icon with hover tooltip displaying the following text:
"The charts below show the average number of days to complete each step of the payment process for payments that reached beneficiaries’ bank accounts on the given date. Therefore, only completed payments are displayed. Your worst performing panchayats are shown first."

**On the TA/GRS info labels**
"Mobile no" --> "Mobile"
"Step 1 average" --> "Average days from muster roll closure to entry"
"Step 1 total transactions" --> "Total transactions"

**Comment by ravisuhag** [comment]
fixed d913b6e
