### ISSUE TITLE
Improve information hierarchy at top of discrete page

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#29]
There is a ton of info at the top of the discrete page, but it's not structured very well.

![image](https://cloud.githubusercontent.com/assets/5039693/14475193/bf188ac8-00ce-11e6-90d0-11191a183e68.png)

Similar to the overview page, there should be a sub-header called "Performance of Your Panchayats". Under this can be the sentence of explanatory text. The unmapped panchayats alerts can go beneath that.

Right now it's hard to understand the context of the unmapped alerts because there isn't header text telling you you're on the panchayat performance page.

Open to suggestions on how to improve this as well.

**Comment by ravisuhag** [comment]
Fixed
