### ISSUE TITLE
Delayed musters not displaying

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#3]
Musters not displaying on delayed musters page.

The API is returning data. Example response for GUNOR block:
[ { step: 'ds_t2',
    msr_no: '4835',
    work_name: 'कपिलधारा कूप निर्माण कार्य अरविन्द सिंह / रामप्रसाद ग्राम बरहाकला',
    work_code: '1709003031/IF/9993707578',
    start_date: '14/03/2016',
    end_date: '20/03/2016',
    panchayat_name: 'BARHAKALA' },
  { step: 'ds_t2',
    msr_no: '4868',
    work_name: 'kapildhara koop umashankar /baijnath',
    work_code: '1709003031/IF/9993701022',
    start_date: '14/03/2016',
    end_date: '20/03/2016',
    panchayat_name: 'BARHAKALA' },
  { step: 'ds_t2',
    msr_no: '4872',
    work_name: 'kapildhara koop keshkumar.babulal rajput',
    work_code: '1709003031/IF/9993701023',
    start_date: '14/03/2016',
    end_date: '20/03/2016',
    panchayat_name: 'BARHAKALA' },
  { step: 'ds_t2',
    msr_no: '4876',
    work_name: 'kapildhara koop ramlal/kadhora',
    work_code: '1709003031/IF/9993701021',
    start_date: '14/03/2016',
    end_date: '20/03/2016',
    panchayat_name: 'BARHAKALA' },
  { step: 'ds_t2',
    msr_no: '4952',
    work_name: 'sudur gram sampark sadak fulare ke khet se hajari lal ke khet tak gram dobha',
    work_code: '1709003010/RC/22012034297198',
    start_date: '14/03/2016',
    end_date: '20/03/2016',
    panchayat_name: 'DOBHA' },
  { step: 'ds_t2',
    msr_no: '5001',
    work_name: 'KAPIL DHARA KOOP NIRMAN KARYA JAY KARAN SINGH S/O SUJAN SINGH OT',
    work_code: '1709003027/IF/9993691598',
    start_date: '14/03/2016',
    end_date: '20/03/2016',
    panchayat_name: 'KOT' } ]

**Comment by edodge** [comment]
Update:

I'm not sure how the employee names are being pulled in. I think that part of the code got dropped when we switched to mirroring the data.

I will merge the employee info in SQL.

**Comment by edodge** [comment]
- [ ] Update SQL queries to merge in employee data
- [ ] Update API

**Comment by angelaambroz** [comment]
What in the world.

**Comment by edodge** [comment]
My bad
