### ISSUE TITLE
Shorten profile page fields under account settings

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#38]
We want to make sure accounts stick to an individual person rather than to a position (for example, BDO of a certain block). To make this a little harder we should not allow them to change the profile information like name, etc.

We will display the first name, last name, and region name(s) but not allow them to change those fields.

We will only allow them to change these fields:
Personal email
Work email
Mobile no

All other fields we should remove from the profile screen.

The Account screen can stay as it is.

**Comment by ravisuhag** [comment]
Fixed
