### ISSUE TITLE
Update current/delayed musters tables based on new API response

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#4]
The current and delayed musters API responses now include all the information prepped for display on their respective pages. Most of the work is being done in SQL.

Sample current muster response:

{ musters:
   [ { msr_no: '5221',
       work_name: '14 VA VITT C C ROADR PATIDAR DHARMSALA K PAS SE SANTILAL K GHAR',
       panchayat_name: 'ICHHAPUR',
       closure_date: '22-03-2016',
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '5222',
       work_name: 'SUDUR KHET SADAK PIPARI ROAD SE PATIDAR KE KHET T',
       panchayat_name: 'ICHHAPUR',
       closure_date: '22-03-2016',
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '5223',
       work_name: 'सुदुर ग्राम सडक ग्रेवल मार्ग खेत सडक गंधावड रोड गव',
       panchayat_name: 'ICHHAPUR',
       closure_date: '22-03-2016',
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '5236',
       work_name: 'med bandhan giraja bai narayan ts n.1122',
       panchayat_name: 'BAIJAPUR',
       closure_date: '22-03-2016',
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '5295',
       work_name: 'medh bandhan mahesh gangaram ts no. 911',
       panchayat_name: 'AGHAVAN',
       closure_date: '22-03-2016',
       name: 'Unmapped',
       mobile_no: 'Unmapped' } ],
  mapping: { total_panchayat_count: 43, grs_panchayat_count: 0 } }

Sample delayed muster response:

{ musters:
   { ds_t2: [ { msr_no: '4835',
       work_name: 'कपिलधारा कूप निर्माण कार्य अरविन्द सिंह / रामप्रसाद ग्राम बरहाकला',
       panchayat_name: 'BARHAKALA',
       closure_date: '20-03-2016',
       days_pending: 17,
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '4868',
       work_name: 'kapildhara koop umashankar /baijnath',
       panchayat_name: 'BARHAKALA',
       closure_date: '20-03-2016',
       days_pending: 17,
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '4872',
       work_name: 'kapildhara koop keshkumar.babulal rajput',
       panchayat_name: 'BARHAKALA',
       closure_date: '20-03-2016',
       days_pending: 17,
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '4876',
       work_name: 'kapildhara koop ramlal/kadhora',
       panchayat_name: 'BARHAKALA',
       closure_date: '20-03-2016',
       days_pending: 17,
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '4952',
       work_name: 'sudur gram sampark sadak fulare ke khet se hajari lal ke khet tak gram dobha',
       panchayat_name: 'DOBHA',
       closure_date: '20-03-2016',
       days_pending: 17,
       name: 'Unmapped',
       mobile_no: 'Unmapped' },
     { msr_no: '5001',
       work_name: 'KAPIL DHARA KOOP NIRMAN KARYA JAY KARAN SINGH S/O SUJAN SINGH OT',
       panchayat_name: 'KOT',
       closure_date: '20-03-2016',
       days_pending: 17,
       name: 'Unmapped',
       mobile_no: 'Unmapped' } ],
     ds_t5: [],
     ds_t6: [],
     ds_t7: [],
     ds_t8: [] },
  mapping:
   { total_panchayat_count: 83,
     grs_panchayat_count: 4,
     ta_panchayat_count: 83 } }

**Comment by ravisuhag** [comment]
@edodge  did you push this code? I am still getting the old response.

**Comment by edodge** [comment]
Let me check

**Comment by edodge** [comment]
Looks like I forgot to push it. Please check now.
