### ISSUE TITLE
Panchayats with no data not handled correctly on block version discrete view

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#52]
Try panchayat "arjuni tikri" under block Gunderdehi. Nothing triggers on the chart portion of the application. It should show a chart with the "No data" overlay.

**Comment by ravisuhag** [comment]
@edodge  this is happening because some panchayats are in the grouping but their data is not there. for e.g. bagheli.

**Comment by edodge** [comment]
@ravisuhag for those cases we need to show the "no data" chart.
