### ISSUE TITLE
Summary stats on top of muster tables

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#58]
Number of musters -- take from length
Average days pending -- add to API

Provide explanatory text

**Comment by edodge** [comment]
@ravisuhag can you take the mean days pending within JS? don't want to add a top level to the api response just for a basic stat.

**Comment by ravisuhag** [comment]
Let me see. We can add it on node side maybe.

**Comment by edodge** [comment]
Closing in favor of redesign.
