### ISSUE TITLE
Add "Cumulative days" above chart legend (overlay legend)

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#64]

**Comment by ravisuhag** [comment]
@edodge  It doesn't look good. I think we should skip it. Let me know. 
<img width="1680" alt="screen shot 2016-06-27 at 10 45 12 am" src="https://cloud.githubusercontent.com/assets/2075279/16369147/44538d62-3c54-11e6-9869-1eb4abc4edae.png">

**Comment by edodge** [comment]
@ravisuhag let's skip.
