### ISSUE TITLE
Date mismatch on charts when selecting different date ranges

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#7]
The axes should be set to exactly 30/60 days depending on the selection, regardless of the dates for which transaction data is available. The discrete charts appear to be doing this correctly, but not the bottom chart on the overview page.

Overview page:

![image](https://cloud.githubusercontent.com/assets/5039693/14397678/d2ba59aa-fdac-11e5-93d3-4ada5f3f1991.png)

Discrete page:

![image](https://cloud.githubusercontent.com/assets/5039693/14397742/5aace288-fdad-11e5-9454-34a85ff9abc4.png)

**Comment by edodge** [comment]
@ravisuhag possibly related issue. Full date range isn't being shown when "All available dates" selected on discrete view.

![image](https://cloud.githubusercontent.com/assets/5039693/14476046/7de480f2-00d3-11e6-88e0-19df3d479a3b.png)

Feel free to open a new issue if this is separate issue.

**Comment by ravisuhag** [comment]
Fixed

**Comment by edodge** [comment]
Data for the block goes back to 1 April 2014 -- panchayat data should also go back that far for "All available dates".
