### ISSUE TITLE
Checkbox alignment on overview page

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#8]
Checkboxes are misaligned (see screenshots).

<b>Machine</b>
Macbook Pro (El Capitan)
<b>Screen resolution</b>
1280x800
<b>Browsers</b>
Chrome 49.0.2623.110 (64-bit)
Safari 9.1 (10601.5.17.4)
Firefox 45.0.1

Issue on Chrome:

![image](https://cloud.githubusercontent.com/assets/5039693/14398322/3a84ca1c-fdb1-11e5-80b6-e2cb13a9d56d.png)

Issue on Firefox:

![image](https://cloud.githubusercontent.com/assets/5039693/14398401/d2fe8422-fdb1-11e5-9202-e2d290cb20cf.png)

**Comment by ravisuhag** [comment]
Fixed with new layout.
