### ISSUE TITLE
Enable forgotten password feature

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#90]

**Comment by edodge** [comment]
@ravisuhag what do you need from me for this?

**Comment by ravisuhag** [comment]
Sendgrid or mailchimp api token info.

**Comment by edodge** [comment]
@ravisuhag sent you this on slack. shouldnt the forgot password feature be on the login page? right now it's assuming the person can log in in order to access the forgotten password feature.

**Comment by ravisuhag** [comment]
Implemented.
