### ISSUE TITLE
Sort issue

### ISSUE THREAD

**Issue by edodge** [hks-epod/paydash#93]

**Comment by edodge** [comment]
@ravisuhag 

check out user test_three

when current musters are all 0 and delayed musters are all 0, sorting by current musters gives a different sort order than sorting by delayed musters. why is this? shouldn't the sort be stable?

**Comment by edodge** [comment]
also -->
sort on name and 'JWALA KHELWAR' ends up near the end of the sort. this is because javascript is sorting names that start with an uppercase letter before names that start with a lowercase letter. i fixed this on api side by doing sort comparisons on lowercase version of the name. this needs to be fixed on app side as well.

**Comment by ravisuhag** [comment]
@edodge  fixed the current and delayed sort issue.  I was already using the lowercase sort. 

But still, there is a small bug I am not able to figure out. When current and delayed are all zero. Sort by Name and Delayed should also remain same but somehow one card comes on top that also at few places only. Looking into it.

**Comment by ravisuhag** [comment]
Closing for now.
